name: All Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test

      - name: Build for Docker
        run: make build-for-docker

      - name: Build for Docker
        run: |
          tag=${GITHUB_REF##*/}
          docker build -t ghcr.io/${{ github.actor }}/httpbun:$tag .
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/${{ github.actor }}/httpbun:$tag
