name: Container Run


on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l -o errexit -o pipefail {0}

jobs:

  all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run container
        run: |
          set -o xtrace
          sudo apt-get install --yes mkcert libnss3-tools
          mkcert -install
          mkcert -cert-file '/tmp/cert.pem' -key-file '/tmp/key.pem' httpbun.local
          echo '127.0.0.1 httpbun.local' | sudo tee --append /etc/hosts
          docker run \
            --name httpbun \
            --detach \
            --publish 443:443 \
            --volume /tmp:/tmp:ro \
            --env HTTPBUN_TLS_CERT=/tmp/cert.pem \
            --env HTTPBUN_TLS_KEY=/tmp/key.pem \
            --pull always \
            sharat87/httpbun
          sleep 1

      - name: Test
        run: |
          set -o errexit
          set -o xtrace

          curl --include --silent --show-error --fail --location https://httpbun.local/any

      - name: Logs
        if: always()
        run: |
          docker logs httpbun
