name: Publish

on:
  workflow_dispatch:

jobs:

  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test

      - name: Build all
        run: make build-for-docker build-all

      - name: Push to GHCR
        run: |
          tag=${GITHUB_REF##*/}
          docker build -t ghcr.io/${{ github.actor }}/httpbun:$tag .
          if [[ $tag == master ]]; then
            docker build -t ghcr.io/${{ github.actor }}/httpbun:latest .
          fi
          docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push --all-tags ghcr.io/${{ github.actor }}/httpbun

      - name: Publish to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "bin/httpbun-darwin-amd64;bin/httpbun-linux-amd64;bin/httpbun-windows-amd64.exe"
          update_latest_release: true
          overwrite: true
          verbose: true
          draft: false
