name: Publish

on:
  workflow_dispatch:

  push:
    branches:
      - "master"

  release:
    types:
      - published

  pull_request:
    branches:
      - "master"

jobs:

  all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test

      - name: Build
        run: make build-for-prod build-for-docker

      - name: Upload package to S3
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          make upload-package

      - name: Push Docker images to GHCR
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          tag=${GITHUB_REF##*/}
          docker build -t ghcr.io/${{ github.actor }}/httpbun:$tag .
          if [[ $tag == master ]]; then
            docker build -t ghcr.io/${{ github.actor }}/httpbun:latest .
          fi
          docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push --all-tags ghcr.io/${{ github.actor }}/httpbun

      - name: "Identify version"
        if: |
          success() && github.event_name == 'release'
        run: |
          make build-all
          echo "release '${{ github.event.release.id }}' '${{ github.event.release.name }}' '${{ github.event.release.tag_name }}'"
          file=bin/httpbun-darwin-amd64
          curl --request POST \
              --header "Content-Type: $(file -b --mime-type $file)" \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              --header "Accept: application/vnd.github.v3+json" \
              --upload-file "$file" \
              "https://uploads.github.com/repos/sharat87/httpbun/releases/${{ github.event.release.id }}/assets?name=$(basename "$file")"
