name: Publish

on:
  workflow_dispatch:

  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

jobs:

  all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run:
          sed 's/ /=/' .tool-versions | tee -a "$GITHUB_OUTPUT"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.versions.outputs.golang }}

      - name: Test
        run: make test

      - name: Build
        run: make docker

      - name: Push Docker images to GHCR and DockerHub
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          tag="${{ github.ref_name }}"
          if [[ $tag == master ]]; then
            tag=latest
            docker tag httpbun "${{ secrets.DOCKER_HUB_USERNAME }}/httpbun:${{ github.sha }}"
          fi
          docker tag httpbun "${{ secrets.DOCKER_HUB_USERNAME }}/httpbun:$tag"
          docker tag httpbun "ghcr.io/${{ github.actor }}/httpbun:$tag"
          docker login ghcr.io --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"
          docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker push --all-tags "ghcr.io/${{ github.actor }}/httpbun"
          docker push --all-tags "${{ secrets.DOCKER_HUB_USERNAME }}/httpbun"
